### ISSUE TITLE
mp3 TXXX/releasetype tag not showing up

### ISSUE THREAD

**Issue by hiccup2** [phw/picard-daily#3]
Thanks for making these 'dailies' available.
It's interesting for taking a look at what's going on and doing some testing.

Here's something I observed just now.
But it could very well be me doing something dumb, and I also haven't checked if this happened with older regular releases. (call me lazy)
I'm pretty sure this mp3 file:
https://www.dropbox.com/scl/fi/v8ly5nybpkswrq28wrv3t/01-test-test.mp3?rlkey=hrgnvnaq6yy3mkeg4izoxlvfh&dl=0
contains a tag: TXXX/releasetype with the value: release type test
But when loading it into the latest daily (Version 2.10.0.dev1 (293-3018d527.20230920004338) it doesn't show up at all.
Is this me?

edit:
It looks there is also something wrong with Picard writing such a 'release type' tag.
Out-of-the-box It will write it for FLAC files (RELEASETYPE), but while the preview suggests it gets written for MP3 and APE also, it looks like it does not actually get written for these file types.
Also, I just now saw that the tag mapping table says it should write TXXX:MusicBrainz Album Type, but a release can be a single, so the wording Album might be incorrect? So why not just TXXX:releasetype?

**Comment by phw** [comment]
This is actually expected behavior. The name of your TXXX tag is `releasetype`, which conflicts with the internal name of the "releasetype" tag used by Picard. In order to avoid that the data then gets written back based on the mapping to `TXXX:MusicBrainz Album Type` the tag gets stored as the hidden variable `_id3:TXXX:releasetype`.

You can use this in scripting (with `%_id3:TXXX:releasetype%`), but variables are currently not available for editing in the UI.

You can use the "View script variables" plugin to inspect those variables:

![grafik](https://github.com/phw/picard-daily/assets/29852/5e311d21-f466-4117-9903-bfeab9a327fc)

So you either need to use scripting if you want to manipulate the data. Or you can use a different tag name in order to avoid this conflict. E.g. you could use `TXXX:MusicBrainz Album Type` and by this use the tag also used by Picard.

**Comment by phw** [comment]
If you want to see in detail which of Picard's tags gets written to which fields in the various tagging format this all documented at https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html
